name: Deploy Website to HostGator with Docker

on:
  push:
    branches:
      - main

# This workflow will build and deploy a Docker container to HostGator

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/domdevops-portfolio-1:latest

      - name: Deploy to HostGator
        run: |
          ssh user@your-server-ip << EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/domdevops-portfolio-1:latest
          docker stop portfolio-container || true
          docker rm portfolio-container || true
          docker run -d -p 80:8080 --name portfolio-container ${{ secrets.DOCKER_USERNAME }}/domdevops-portfolio-1:latest
          EOF